# Generated by Django 2.1.3 on 2018-11-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_product', models.CharField(choices=[('WM', 'Warehouse Management'), ('WFM', 'Workforce Management'), ('EMS', 'Event Management'), ('HUB', 'HUB'), ('RPT', 'Report'), ('REFS', 'REFS')], max_length=100)),
                ('app_server1', models.CharField(max_length=100)),
                ('app_server2', models.CharField(blank=True, max_length=100)),
                ('app_os', models.CharField(choices=[('WINDOWS 2008', 'Windows Server 2008'), ('WINDOWS 2012', 'Windows Server 2012'), ('WINDOWS 2016', 'Windows Server 2016'), ('RHEL 7', 'Red Hat Linux 7'), ('RHEL 6', 'Red Hat Linux 6'), ('AIX 6', 'AIX 6'), ('AIX 7', 'AIX 7')], max_length=100)),
                ('app_cluster', models.IntegerField(default=0)),
                ('app_port', models.CharField(max_length=100)),
                ('refs_url', models.URLField()),
                ('db_name', models.CharField(max_length=100)),
                ('db_server1', models.CharField(max_length=100)),
                ('db_server2', models.CharField(blank=True, max_length=100)),
                ('db_type', models.CharField(max_length=100)),
                ('db_os', models.CharField(choices=[('WINDOWS 2008', 'Windows Server 2008'), ('WINDOWS 2012', 'Windows Server 2012'), ('WINDOWS 2016', 'Windows Server 2016'), ('RHEL 7', 'Red Hat Linux 7'), ('RHEL 6', 'Red Hat Linux 6'), ('AIX 6', 'AIX 6'), ('AIX 7', 'AIX 7')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnvHdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_owner', models.CharField(max_length=100)),
                ('env_tier', models.CharField(choices=[('DEV', 'Development'), ('TEST', 'Testing'), ('QA', 'QA'), ('TRAIN', 'Training'), ('PROD', 'Proudction')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnvPatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('errors', models.IntegerField(blank=True)),
                ('env_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envmgmt.EnvDtl')),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_release', models.CharField(max_length=100)),
                ('patch_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prg_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='envhdr',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envmgmt.Project'),
        ),
        migrations.AddField(
            model_name='envdtl',
            name='env_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envmgmt.EnvHdr'),
        ),
    ]
