# Generated by Django 2.1.3 on 2018-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envhdr',
            name='env_owner',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('CUSTOMER', 'Customer')], max_length=40),
        ),
    ]
