# Generated by Django 2.1.3 on 2018-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmgmt', '0002_auto_20181113_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='envhdr',
            name='env_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
