# Generated by Django 2.1.3 on 2018-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envmgmt', '0003_envhdr_env_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envdtl',
            name='refs_url',
            field=models.CharField(max_length=100),
        ),
    ]
